version: '3.3'

services:
  db:
    container_name: ${DB_HOST}
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    command: -p ${DB_PORT}
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
    #  - ../backend/:/backend
      - static_value:/backend/static/
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 9999:8000

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend


volumes:
  static_value:
  db_value: